### ISSUE TITLE
Example usage or how-to

### ISSUE THREAD

**Issue by anissen** [markknol/hx-googlecast-externs#1]
This repository is very interesting and opens up some amazing possibilities for apps and games. 
However, it would be very _nice_ with a minimal working example or guide on how to get started with these externs. If you could find the time to make this, it would be greatly appreciated :+1:

**Comment by markknol** [comment]
Good plan. Most code is copy pastable from the chromecast api, but to get started it might be handy to provide some startup code.

**Comment by markknol** [comment]
If you are REALLY interested and in a hurry ill send you some code right away.

**Comment by anissen** [comment]
Thanks for the quick reply. I am very interested in pursuing the possibilities that the Chromecast offers, especially for local-multiplayer games (inspired, among other things, by [your own work](http://www.trickytitans.com/) in that genre). I'm not in a hurry, however. In fact I'll be travelling for almost a month from tomorrow. 
But I'm happy to hear that you're positive towards my proposal - I think it could be a win for the Haxe community at large :)

**Comment by anissen** [comment]
Great, thanks :+1:
